# -*- truncate-lines: nil -*-



* A 200-300 word description of what is featured in each image, so that they are contextualised for readers :REV1:GREEN:
:DESCRIPTION:
- The photographs show a series of seven digital archival prints, each 141 x 121 mm on Hahnemuhle Museum Etching paper, presented underneath glass on a display table at Galway Arts Centre.

- The Fearn series (15 small-format Giclée prints) is one of five series of generative art featured in Mícheál's solo show at Galway Arts Centre in December 2021. The other series, titled Beith, Coll, Luis and Sail, comprised 16 medium format prints - 400 x 400 mm. The show, which combined giclée prints, audiovisual installation and live solo performance on harp, voice and electronics, represented Mícheál's emotional response to the music encoded in the Bunting manuscripts, a collection of early Gaelic harp music and songs from the turn of the 1800s.

- The 121 x 142 mm dimensions of each piece in the Fearn series are in homage to the dimensions of the collecting field paper of Edward Bunting, while the paper chosen (Hahnemuhle Museum Etching paper) is mindful of the laid-paper technology which had recently emerged at the time Bunting collected this harp music.

- During Winter 2021 it was uncertain if the physical exhibition would proceed due to covid lockdown restrictions. Consequently Mícheál created a virtual audiovisual exhibition of the work online, as well as physical fine-art prints and digital display of the images mounted in the physical exhibition space, with accompanying generative audio. Happily in-person viewing of the exhibition went ahead!

- The form of the pieces in the Fearn series comprises intersecting music staves and bordered paths reminiscent of Celtic knot-work, with clouds of musical note-heads escaping their confines. 

- Mícheál applied a rule-based colour palette, based on a gradient of reds to yellow-greens in \"north to south\" direction, with a gradient of blue-greens to violets in the \"west to east\" direction.
  
:END:
:LOGBOOK:
- Note taken on [2023-03-21 Tue 18:43] \\
  First draft at 300 words. Ready for a polish ideally, if Gaye has time to review Wed - Fri. Ideally I'll get to meet them some eve before the weekend. I'll need to check and then clear with James O'S, or vice versa!
- Note taken on [2023-03-17 Fri 10:59] \\
  Good paragraphs, not all keepers. Next step integrate GAC technical description where appropriate.  Also consider fill in the blanks content and introduce if strong and appropriate in this section.
:END:

* A 300-500 word biographical note (written in the third person) :REV1:AMBER:
:BIO:
- Mícheál is a multimedia artist working primarily with harp & voice performance, computer code, installation. He is a recipient of Irish Arts Council Agility (2021), Traditional Arts Bursary (2017) and Deis Recording & Publication (2017) Awards. Mícheál has performed solo harp & voice concerts at Achill International Harp Festival and Scoil na gCláirseach Festival of Early Irish Harp, and his generative art has been exhibited at Naas Art & Culture Centre, Galway Arts Centre [and the Lord Mayor's Pavillion, Cork.]

- Faithful to historical practices, Mícheál sings with the harp on his left shoulder and employs specialised fingernail techniques ("lúthchleasa") to shape the resonance of these metal-strung instruments. His arrangements of Bunting manuscript pieces, guided by the rhythms of his "sean-nós" singing, breathe fresh life into Ireland's ancient harp music for contemporary audiences.

- Mícheál gravitates equally towards the ancient and the emergent.  He codes custom algorithms to make and share generative audiovisual art which reflects and nourishes his process of engaging with the early Gaelic harp on the harp's own terms.

- In recent years...Micheal has integrated digital art skills with his [existing] strong background in harp/voice performance
   As a multimedia artist, Micheal curates beautiful and unique audiovisual experiences for audiences across three interweaving and artistically fertile strands:
     Historical: historically viable performance of ancient harp pieces from archival manuscripts and collections
     Traditional: arrangement and performance of historical repertoire, returning these pieces faithfully into the common repertoire
     Contemporary: performance of improvised music, with associated generative artwork and digital sound art, bringing the early Irish harp into a wider context (than purely historical or traditional) for contemporary audiences

:END:
:LOGBOOK:
- Note taken on [2023-03-21 Tue 14:53] \\
  consider story telling style here!
- Note taken on [2023-03-20 Mon 18:21] \\
  ;;; In recent years...Micheal has integrated digital art skills with his [existing] strong background in harp/voice performance
  ;;; As a multimedia artist, Micheal curates beautiful and unique audiovisual experiences for audiences across three interweaving and artistically fertile strands:
  ;;; Historical: historically viable performance of ancient harp pieces from archival manuscripts and collections
  ;;; Traditional: arrangement and performance of historical repertoire, returning these pieces faithfully into the common repertoire
  ;;; Contemporary: performance of improvised music, with associated generative artwork and digital sound art, bringing the early Irish harp;;; into a wider context (than purely historical or traditional) for contemporary audiences
  ;;; *ambitious*
  ;;; Micheal develops and programs algorithms (computer code) representing rules [within which unique visual art pieces are generated]
  ;;; generative visual art reacts in real time to sampled or generated harp audio...
  ;;; carefully incorporating randomness so that audiovisual experience is ever-evolving and unique
  ;;; high quality digital archival prints, working with fine-art printers (and framers)
  ;;; situating his digital art in the arc of art-history ... contemplating the place of generative coded art in the wider arc of art-history...
  ;;; using computer code as a medium for padding out the full spectrum of viable possibilities suggested by the sparse archive of harp music
  ;;; engaging with the digital archive using digital tools
  ;;; engaging with the affordances emerging digital software and hardware... (ref essay), to create immersive audiovisual installation experiences for audiences
  ;;; During a 2017 Traditional Arts Bursary Micheal began painting his emotional response to music encoded in the Bunting harp manuscripts. A 2020 Kildare Council [Local Authority Arts] Grant saw Micheal combining this physical artwork with creative coding, drawing on his engineering background, towards and exhibition and concert at Naas Arts & Culture Centre.  ...expand this to Galway Arts Centre...
  ;;; Micheal is an emerging multimedia artist working with live harp & voice performance and audiovisual exhibitions.
  ;;; Micheal has performed as a singer and fiddle player for decades, a foundation upon which he has established a deep practice since 2011 with the early Irish harp.  [Mention time split / parallel careers?]
- Note taken on [2023-03-17 Fri 11:11] \\
  250 words or so, still short.  Can customise and elaborate generously, using my what,how,why prompts and fill in the blanks, and also original bio I provided GAC.
:END:

* A 500-1000 word reflection on your artistic practice, in the context of the artworks which have been selected for the book. :REV2:RED:
:REFLECTION:

- Singing is at the centre of my artistic practice. Orbiting this centre is the resonance of the early Gaelic harp. As a multimedia artist I integrate fine-art digital print, audiovisual installation and live performance to connect outwards from this centre with contemporary audiences. Creating both online and in real life (IRL) experiences rooted in the oral traditions I have inherited, I engage the emotions of today's viewer in order to make heart-felt connections with my subject matter, the resonant nature of singing with harp. I want my audiences to have a visceral, kinesthetic response to my work; only afterwards realising it was made using computer code.

- I consider the singing human larynx as an original, primal, embodied technology with infinite possiblilities of movement, sensitively influencing the flow of breath and making it audible through resonance. I make connections between singing and the technology we make - ancient carbon-based technology like the early Gaelic harp and newly emerging silicon-based digital "Web 3.0" technologies built on the blockchain concept.  For me the very old and the very new are similarly fertile creative spaces in a global village, folding over onto each other from opposite ends of the same spectrum.

- Generative art has an established place in art history, pioneered by such visual artists as Vera Molnar. In the musical sphere composers like John Cage composed since the 1950s using chance procedures.  In the pre-computer era of these artists, their rule-based algorithms were implemented with traditional art forms such as painted canvas and orchestra. Nowadays generative art is enjoying a renaissance, created by artists using modern computer languages and presented using a cornucopia of both mature technologies (such as fine art inkjet printers and surround sound audio speakers) of ever increasing fidelity, as well as newer internet-enabled fixed and mobile devices (such as 8K+ smart displays, and smart phones/tablets). Happily, estabished and emerging digital media such as these are ideal playgrounds for generative artists like myself to make and share work, since these media are designed to afford combined visual and musical forms, and also since these media reach a global audience via the internet browser. 

- During a 2017/2018 Irish Arts Council bursary I began painting my emotional response to music encoded in the Bunting harp collection. Since I have a strong engineering background I subsequently combined this physical artwork with creative coding. I chose the internet browser as my primary medium after researching a broad range of computer languages over the course of 2020 and 2021.  My "virtual studio" ecosystem now comprises a text editor called emacs, code written in a computer language called clojurescript, with an internet browser window open on my screen rendering audiovisual outputs from my code as I work.  Working in this way I have come to realise how well suited to my process are physical exhibitions and solo harp/voice concerts. This realisation came when I demonstrated to myself that I can render to high-resolution, and then print, the art I make in and for the browser, so that I access the best of both worlds - the reach and facility of the browser, with the warmth, texture and visual fidelity of a fine-art print.  As well as exhibitions and performances, I find inspiration in sharing my work in progress with like-minded artists; this type of sharing is typical of many generative artists who regularly share their work in progress, as do I, on a variety of social media platforms. [include!!! tag, and via website!!!]

- My process for my Lúthchleasa collection involved coding five custom computer algorithms which generates variable digital images. Though variable each image is unique and repeatable based on a digital signature which determines all randomness in the image. Think of this signature as a seed or DNA for all the variability of the specific audiovisual output. I generated about 1000 images from each of the five algoriths. I then curated a series of 100 images from each of these 5 sets. During a last curation step I selected 16 images for printing in medium 400 x 400 mm format from the Beith, Coll, Luis and Sail algorithms, and 15 images for printing in small 141 x 121 mm format from the Fearn algorithm. The medium format prints were wall-mounted, while the 15 small format pieces from the Fearn series were displayed in the exhibition on two tables. Photographs of 7 of these tabletop prints are shown.  [Images use in av installation and performance]
  
- I am investigating my belief that there is a link between the resonating patterns expressed visually and sonically in early Irish music and art.  I believe theses ideas are rule-based, geometric, with variability / deviations from the rules expressible with randomness.  I don't consider the music collected by Bunting to be a static unchanging set of relics. Instead I am convinced the musical ideas contained in the Bunting manuscripts [and other related archival collections] represent datapoints in a broad, dynamic and rich spectrum of possibilities.  In Lúthchleasa, I am exploring and reimagining this spectrum using computer code to create visuals and sounds with simple rules, primitive geometric shapes and randomness. 

- I am drawn to the subject of musical resonance because it is a universal human experience which finds regional and personal expression. This led me to think about whether the visual art on the Trinity harp (which includes Celic knot-work, overlaid lozenges, and circular motifs) express simlar ideas to those represented by the music the harp was designed for. I created the Lúthchleasa collection to explore this thought with abstract visual forms and sound samples.

- I don't gravitate towards academic study of early Gaelic harp music. Instead I take an experimental approach, curating experiences of resonance using my own voice and body in collaboration with my harp, and a range of multimedia technologies. I have come to understand that my approach needs to be iterative, playful and curious. 

- My questioning of conventional interpretations of the music represented in the Bunting manuscripts is expressed in the curation of the Fearn series in GAC, where I chose not to mount the pieces on the wall but rather flat on a display table, suggesting another point of view
  
- To me Lúthchleasa [] represents a mindfully curated attention echo-chamber, appropriating the latest emerging technology to amplify for myself and for audiences the ideas of resonance as represented in early Gaelic harp music and art.

- In the process of creating Lúthchleasa [], some ideas crystalised as I hoped while others proved too ambitious in the timescales available and so form the seeds for future work!
:END:
:LOGBOOK:
- Note taken on [2023-03-26 Sun 12:09] \\
  Gen visual and audio pioneer section needs work!
- Note taken on [2023-03-26 Sun 11:19] \\
  improvisational nature of harp...
  
  share this writing with Ann!
- Note taken on [2023-03-26 Sun 10:59] \\
  Web technologies democratise traditional arts
- Note taken on [2023-03-26 Sun 10:35] \\
  Gaye feedback:
  For my part I found it most interesting and engaging. I completely understood your motivation and intention and your emotional connection the art, music and coding.  Really interesting.  I was quite excited to see the art pieces which are beautiful. Loved the signficance of the paper.
  
  Chris feedback:
  Loved the combining of the very modern as in the coding with the ancient. 
  ...paraphrase... he really got my idea that the oral tradition was one filled with variation and how I see coded audiovisual media are much closer to an oral tradition for the global village, as being more suitable to representing this tradition for today, and that that the print technology of Bunting's era brought with it an independent message (which has been convoluted across the general understanding of early Gaelic harp music) that the musical "snapshot" was fixed, unvarying.  This idea is validated by audio recording era folk and sean nos singers... such as Colm Ó Caoidheáin and Sorcha Ní Ghuairim, as well as instrumental artists such as ... performing the same song in different ways on different occassions sometimes years apart.
- Note taken on [2023-03-26 Sun 10:32] \\
  About to start rewrite! Rev2 here goes!
- Note taken on [2023-03-21 Tue 17:11] \\
  At 990 odd words. Well done me! I'll call that a first draft :)
- Note taken on [2023-03-21 Tue 16:41] \\
  What about Agnes Martin ... music is accepted as pure emotion, but from art they demand explanation.  Also didn't Af Klimt talk about music and visuals, also Josef Albers....
- Note taken on [2023-03-21 Tue 16:38] \\
  I do find it really valuable to be able to express HOW I respond in my art emotionally to music in the Bunting archive... how does they things map even if not 1:1.  Colour palettes, modes, ... what I would like to consider in Juxt!  Can I summarise a kernel on how and why I do this?  Referencing visual rhythm, harmony etc.....
- Note taken on [2023-03-21 Tue 14:28] \\
  Copying to new BLUE tag and cutting out all hard and fast linkage between early Irish art and my artwork
- Note taken on [2023-03-21 Tue 14:28] \\
  I don't want to make a target for my own back.  A standard to be held to with all my visual art. I choose artistic freedom.
- Note taken on [2023-03-21 Tue 08:12] \\
  Embrace that I'm at early stages.  I'm setting up conditions for my further exploration of luthchleasa LONG TERM.  Its about the ecosystem, boundaries, conditions in which my exploration, experimentation, thrives.
- Note taken on [2023-03-21 Tue 07:54] \\
  Discussion with Gaye and Chris might help to tease out how I express whether singing, or singing and harp is at the centre of my art.  Really it is an intention.  I want to create conditions conducive to me singing daily, with harp, in a world in which voice and resonance in the body, or wrapped around a resonanting harp, is atrophying down the senses and body parts which can engage with the tiny reduced affordances of technologies designed without .... e.g., Ge's image of a giant eye on a finger, as seen by the computer!
- Note taken on [2023-03-20 Mon 18:23] \\
  ;; Structures:
                ;;; storytelling - beginning, middle and end
                ;;; medium / process / understanding of the work (with strong, attention grabbing, end sentence)
                ;;; field notes (use words to create curiosity, share info and provoke closer examination of subject and form)
                ;;;; para to describe where you are, or what exploiring (the general caption)
                ;;;; notes re individual pieces (with attributes)
                ;;; (always lead back to what viewers are seeing)
- Note taken on [2023-03-20 Mon 12:14] \\
  I wish to remain sufficiently general so that I avoid hemming in my artistic freedom, while still expressing the why and worthiness of my harp-specific work so that audiences / viewers will take a closer look at my work (both specifically and overall).
:END:



