# -*- truncate-lines: nil -*-


* A 200-300 word description of what is featured in each image, so that they are contextualised for readers :REV1:AMBER:
:DESCRIPTION:
- The photograph shows a series of seven digital archival prints, each 141 x 121 mm on Hahnemuhle Museum Etching paper, presented underneath glass on a display table.

- The Fearn series (15 small-format Giclée prints) is one of five series of generative art featured in Mícheál's solo show at Galway Arts Centre in December 2021. The other series, titled Beith, Coll, Luis and Sail, consisted of 16 medium format prints - 400 x 400 mm. The show, which comprised giclée prints, audiovisual installation and live solo performance on harp, voice and electronics, represented Mícheál's emotional response to the music encoded in the Bunting manuscripts, a collection of early Gaelic harp music and songs from the turn of the 1800s.

- The 121x142mm dimensions of each piece in the Fearn series are in homage to the dimensions of the collecting field paper of Edward Bunting, while the paper chosen (Hahnemuhle Museum Etching paper) is mindful of the laid-paper technology which had recently emerged at the time Bunting collected this harp music.

- During Winter 2021 it was uncertain if the physical exhibition would proceed due to covid lockdown restrictions. Consequently Mícheál created a virtual audiovisual exhibition of the work online, as well as physical fine-art prints and digital display of the images mounted in the physical exhibition space, with accompanying generative audio. Happily in-person viewing of the exhibition went ahead!

- The form of the pieces in the Fearn series comprises intersecting music staves and bordered paths reminiscent of Celtic knot-work, with clouds of musical note-heads escaping their confines. 

- Mícheál applied a rule-based colour palette, based on a gradient of reds to yellow-greens in \"north to south\" direction, with a gradient of blue-greens to violets in the \"west to east\" direction.

- Micheal would like the viewer to approach the work with awareness of their point of view.  He encourages such awareness through his choiceof displaying the pieces in the horizonal (reminiscent to how museum pieces are displayed, e.g., the Book of Kells) rather than the more traditional choice of vertical wall mounting.  By bringing the viewer physically closer to the artwork, Micheal also encourages a sense of curiosity and accessibilty about the harp music represented.
:END:
:LOGBOOK:
- Note taken on [2023-03-17 Fri 10:59] \\
  Good paragraphs, not all keepers. Next step integrate GAC technical description where appropriate.  Also consider fill in the blanks content and introduce if strong and appropriate in this section.
:END:

* A 300-500 word biographical note (written in the third person) :REV1:AMBER:
:BIO:
- Mícheál is a multimedia artist working primarily with harp & voice performance, computer code, installation. He is a recipient of Irish Arts Council Agility (2021), Traditional Arts Bursary (2017) and Deis Recording & Publication (2017) Awards. Mícheál has performed solo harp & voice concerts at Achill International Harp Festival and Scoil na gCláirseach Festival of Early Irish Harp, and his generative art has been exhibited at Naas Art & Culture Centre and Galway Arts Centre.

- Faithful to historical practices, Mícheál sings with the harp on his left shoulder and employs specialised fingernail techniques ("lúthchleasa") to shape the resonance of these metal-strung instruments. His arrangements of Bunting manuscript pieces, guided by the rhythms of his "sean-nós" singing, breathe fresh life into Ireland's ancient harp music for contemporary audiences.

- Mícheál gravitates equally towards the ancient and the emergent.  He codes custom algorithms to make and share generative audiovisual art which reflects and nourishes his process of engaging with the early Gaelic harp on the harp's own terms.

- Interpreting the Bunting manuscripts for a contemporary audience, Mícheál employs computer code as a collaborative partner to represent these patterns in visual form and expresses in this generative art his emotional response to the music. Lúthchleasa [lu:hxlˈæsə] illuminates ancient music and celebrates the beauty and colour spaces inhabited by early Irish art, reimagining for today the full spectrum of expression felt and heard by harpers and listeners alike centuries ago.
:END:
:LOGBOOK:
- Note taken on [2023-03-17 Fri 11:11] \\
  250 words or so, still short.  Can customise and elaborate generously, using my what,how,why prompts and fill in the blanks, and also original bio I provided GAC.
:END:

* A 500-1000 word reflection on your artistic practice, in the context of the artworks which have been selected for the book. :REV1:RED:
:REFLECTION:
- I am investigating my own intuitive approach to re-animating ancient Irish harping finger-nail techniques. I collectively refer to these techniques as lúthchleasa (an Irish language word which may be translated as athletics).  The artwork provides me a framework on which to record my interpretation of these lúthchleasa. The visual medium of generative art serves to represent visually attributes of my physical playing of these techniques on my harp, and the sounds which result.

- I am communicating my range of responses to the lúthchleasa, representing these responses in visual form to share the emotional, musical, linguistic and physical attributes I associate with each of these lúthchleasa.

- Lúthchleasa / Fearn tells the story of my engagement with these fingernail techniques, as I deepen my understanding of these techniques and the musical ideas they represent.  The nature of generative art is that it is iterative, so I expect to build my story into future versions of the code, and the art work which emerges,  as my understanding and playing of these lúthchleasa techniques on my harp evolves.

- My process involved coding an algorithm which generates variable outputs, each image unique and repeatable based on a digital signature which determines all randomness in the image. Think of this signature as a seed or DNA for all the variability of the image. From a set of circa 200 unique images generated by the algorithm, I curated 15 images for printing and display in the exhibition on two tables. 7 of these images are shown in the photograph.

- The Fearn series of generative artwork represents my emotional response to a specific family of harp techniques (a subset of the full set of lúthchleasa) named in the Bunting as leath leagadh, leagadh anuas, brisidh and crothach aon mhear. From my own experience of playing these techniques, I have grouped them together and assigned (as a memory aid) the ogham symbol Fearn to identify this grouping.

- The noteheads escaping from the staves represents the release of the notes from the "straigh-jacket" / limitations of European music notation             

- I am investigating my own intuitive approach to re-animating ancient Irish harping finger-nail techniques, which I collectively refer to as lúthchleasa.  The artwork provides me a framework on which to record my interpretation of these lúthchleasa, the visual medium of generative art serves to represent visually attributes which I map from my physical playing of these techniques on my harp and the sounds which results.

  # what prompts...
- I am breaking apart / separating / categorising the families of techniques, and examining their attributes

- I would encourage viewers to take a closer looks at the fine detail in the noteheads, and how the attributes of the techniques are mapped to the visuals of each piece in the Fearn series, as indicated by the names.

- The richness of the early Irish harp and visual art traditions keeps me curious and dedicated, especially how to find contemporary and appropriate settings for expressing the ideas for which this instrument and the music it can make is uniquely suited.

- The artwork involved mentorship (both musical with Ann Heymann and visual with Louise Manifold), skills in computer coding of visuals and audio in the browser, travel between Dublin (where I lived at the time) and Galway Arts Centre for site visits and well as production of the exhibition, technology in multiple forms - print, photo, video, computer hardware, remote monitoring of audio visual installation, electronic effects during live performance. 

# how prompts...
- I physically engaged in the creation of the work by playing the lúthchleasa on my harp and absorbing their musicality.  Then I sat and wrote code using a computer keyboard, and viewing the results on a computer screen. I visited the gallery space and through discussions with the gallery team as well as mentorship, decided that displaying the images horizontally rather than the traditional vertical mounting was appropriate, both for the pieces and for architecture of the room.

- I am uniquely presenting the subject by presenting the pieces horizontally, and by abstracting the notes and staves in the Bunting manuscripts, playing with their structure and introducing colour.

- Through experimentation (and happy accidents!) I discovered that carefully introducing randomness into the underlying grid gave a softer more organic feel to the overall composition
  
- I chose the browser as my primary medium by researching a broad range of computer languages over the course of the pandemic.  It became apparent to me how much of human time and attention globally is spent within this browser environment. I also realised how powerful a multimedia medium the browser is already, with additional features being added by browser designers on a daily basis.  A big ah-ha moment was when I demonstrated to myself that I could render to high-resolution and print the art I made in and for the browser, so that I could access the best of both worlds - the reach and facility of the browser with the warmth, texture and visual fidelity of a fine-art print.

- I would like the viewer to approach the work with awareness of their point of view, an awareness encouraged by the choice of the artist to display the pieces in the horizonal (reminiscent to how museum pieces are displayed) rather than the more traditional choice of vertical wall mounting. With a curiosity about how accessible we feel the music represented in the art to be

  
# why prompts...

- I made this work to map out visually the idea of luthchleasanna, giving each technique their territory visually, sufficient to explore long term as my understanding of their emotional content evolves.

- I believe that predictable, repeatable human emotional response is hard-coded into the techniques

- I believe that these responses can be mapped visually, individually and overlapping             
              
- I am investigating my belief that there is a link between the ideas expressed visually and sonically in early Irish music and art.  I belive theses ideas are rule-based, geometric, with variability / deviations from the rules expressible with randomness.  I also believe that music collected by Bunting represents datapoints in a broad dynamic spectrum, not static unchanging relics.  I believe that this spectrum can be reconstructed, using digital art forms and ideas of geometry and randomness.

- Viewers can see this belief coming through in the artwork in my Lúthchleasa collection in several places. This belief takes form in the primative geometric shapes, random distributions of same, and in the combination of attributes (colour, structure,) resulting in emergent complexity. This belief also comes through in how I am linking music and visuals, both in exhibition/installation, and also in live performance. My questioning of conventional interpretations of the music represented in the Bunting manuscripts is expressed in the curation of the Fearn series in GAC, where I chose not to mount the pieces on the wall but rather flat on a display table.

- The emotion which were primary while I made this artwork was calm.   Certainly over the 6 months or so it took to make the work there were times of anxiety and frustration, but on the whole I experienced a sense of calm while methodically creating and combining the functional building blocks of code which represented the visual ideas I wanted to make.  A few times I even experienced surprise and wonder, especially when I introdcued randomness into grid of Fearn... carthesis (sail), 

- The emotions I experience when playing lúthchleasa are... awe, gratitude, excitement, satisfaction, joy, relief, amusement, soothed, buzzing/alert, focussed, proud, 

- Emotion comes through the work through colour, the juxtiposition of hard lines and relaxed structure, notes "flying" away, released from strait jacket.

- During the process I thinking about paths in the Celtic knotwork decorations on my harp, as well as the staves and notes layered on the pages of the Bunting manuscripts. I thought about how I might reverse engineer the layers, a sort of archaelogy of the layers from the compound image.  I also thought about affordances of the browser - linking sounds and visuals             

- Several things inspired this direction.  During my Agility bursary I had with two mentors, Louise Manifold ... and Ann Heymann ... The conversations I had with Louise and Ann inspired the direction.  Earlier in 2017, during an Arts Council Bursary, I began painting.  When I discovered p5.js tutorial of Dan Shiffman in 2019 during the pandemic, I had the realisation that my background in coding was worthwhile for me to begin drawing upon, as I do not have a strong background in traditional art.  I heard from several sources that bringing the main parts of your life into your art is a really good strategy (..read in a great book called Art and Fear by ...), and this resonated with me to begin use computer code to represent using generative art the ideas I have been developing about the harp and singing and their relation to early Gaelic visual art.  ... Frustration of not relating to accepted wisdom of historically informed practice, 

- Learning about art history I found abstract expression (check art history term) fitted well with my approach of representing ideas as abstract colourful forms (Hilma Af Klint, Wassily Kandinsky).  Abstract also seemed to me a good way to consider the early Gaelic art - that these forms and symbols do indeed represent ideas (archetypal forms in nature, breath and speech..).  This way of considering early Gaelic art, and other so-called "primative" art globally, is inspired by my reading of Sensitive Chaos by ...  Taking an abstract approach also fitted with my intuition to relax constraints of directly linking visuals to music, as this allowed the unknown / gaps in the Bunting music to fill themselves in - also this honoured my own intuition from being imbibed in traditional singing and dance music.


# fill in the gaps

- I work in generative art, installation and performance because it allows me to engage with diverse contemporary audiences to reanimate the richness of ideas represented in early Irish harp music, song and art.
              
- I engage the emotions of the viewer in order to make heart-felt connections with my subject matter, the resonant nature of both singing and harp music.

- I created the Lúthchleasa exhibition to express my emotional response to the music encoded in the Bunting manuscripts.
- I created the Fearn series to express my visual mapping of musical attributes associated with four specific fingernail techniques (Lúthchleasa) recorded by Bunting from the last of the early Irish harpers in the 1790s.

- The 121x142mm dimensions of each piece in the Fearn series matches the dimensions of Edward Bunting's field notebook, while the paper chosen () is mindful of the laid-paper technology which had recently emerged at the time Bunting collected this harp music. 

- I am drawn to the subject of musical resonance because it is a universal human experience which finds regional and personal expression.
- I am drawn to the subject of early Irish harp, song and art because of my conviction that they respresent ancient forms of soul nourishment which remain relevant today. 
              
- In the process of creating this work, I gained the experience of successfully delivering an ambitious multimedia exhibtion.
- In the process of creating this work, some ideas crystalised as I hoped while others proved too technically challenging in the timescales available and so formed the seeds for future work.

- I want my viewers to have a visceral, heart-felt response to my work; only afterwards realising/learning it was created using computer code.

- I discovered that my approach needed to be iterative and experimental
- I discovered that my approach needed to be of the hand-curated variety rather than of the long form variety, given (both) the higher artisic and technical challenges of the latter.              

- I find inspiration in sharing my work in progress with like-minded artists; this type of sharing is the M.O. of many generative artists who regularly share their work in progress, as do I, on a variety of social media platforms.

- Singing is at the centre of my art
- Breathing and resonance is at the centre of my art                            

- I don't gravitate towards academic study of early Irish harp music, instead I take an experimental approach, curating experiences of resonance using my own voice and body in collaboration with my harp, and a range of multimedia technologies. (affordances)
              
- My work is a combination of play and cultural inheritance.
              
- To me the most important thing is singing.              

- I make connections between singing and technology - ancient techology like the early Gaelic harp and emerging technology like web3 / blockchain.

- To me this (show) represents a mindfully curated attention echo-chamber, appropriating the latest emerging technology to amplify for myself and for the viewer - even for a short while - the ideas represented in early Gaelic harp music and art.

- I was thinking about whether the art on the trinity harp represents the same ideas as those represented by the music it is designed for, and I created the Lúthchleasa exhibition which explores this idea with abstract forms and sound samples.

:END:
:LOGBOOK:
:END:
