# -*- truncate-lines: nil -*-



* A 200-300 word description of what is featured in each image, so that they are contextualised for readers :REV2:GREEN:
:DESCRIPTION:
The images shown are taken from an exhibition of generative art by multimedia artist Mícheál Ó Catháin, titled \"Lúthchleasa [lu:hxlˈæsə]\". The show combines digital archival prints, audiovisual installation and live solo performance on early Gaelic harp, voice and electronics. It represents Mícheál's emotional response to the music encoded in the Bunting manuscripts, a collection of early Gaelic harp tunes (many with associated Irish-language song texts) hand-notated on paper in real-time from the playing of the old harpers in the period 1792 - c. 1805.

Mícheál's process for his Lúthchleasa collection involved him coding five custom computer algorithms, each capable of generating an infinite number of unique digital images.  Mícheál generated about two thousand images from each of the algorithms. He then curated a series of approximately one hundred images from each of these five sets. During a last curation step he selected a shortlist of sixteen images from his Beith, Coll, Luis and Sail algorithms for fine-art printing on 40 x 40 cm archival paper. He also selected fifteen images from his Fearn algorithm for smaller 14 x 12 cm prints, in homage to the dimensions of the collecting field paper of Edward Bunting.  For Mícheál's exhibition in Galway Arts Centre, the medium format prints were wall-mounted, while the smaller pieces from the Fearn series were exhibited flat on two glass-topped display tables. In an adjacent space the full set of curated images (number about five hundred in all), along with generative audio also coded by Mícheál, were fed by Raspberry Pi mini-computers to five Samsung Crystal 43inch displays & speakers.

Images curated by the editors from each of Mícheál's Beith, Coll, Fearn, Luis and Sail series are shown. The photograph shows seven Fearn series prints, laid on a display table at Galway Arts Centre.  [Images showing guy sitting on bench on front of 3 of the 5 AV screens?]. 
:END:
:LOGBOOK:
- Note taken on [2023-04-02 Sun 16:07] \\
  Great but cut...
  6) The form of the pieces in the Fearn series comprises intersecting music staves and bordered paths reminiscent of Celtic knot-work, with clouds of musical note-heads escaping their confines.
  7) Mícheál applied a rule-based colour palette, based on a gradient of reds to yellow-greens in \"north to south\" direction, with a gradient of blue-greens to violets in the \"west to east\" direction.
- Note taken on [2023-04-02 Sun 16:06] \\
  good line but cut...
  The 121 x 142 mm dimensions of each print in the Fearn series are in homage to the dimensions of the collecting field paper of Edward Bunting, while the paper chosen (Hahnemuhle Museum Etching paper) is mindful of the transition from traditional "laid" to the more industrialised "wove" paper-making technology which happened during Bunting's lifetime.
- Note taken on [2023-04-02 Sun 16:01] \\
  cut but good...
  
  Though each individual output generated is unique, Mícheál can choose to re-render any one of these, based on a seed number which determines all variability in the image.
- Note taken on [2023-03-29 Wed 19:21] \\
  Martin:
  description...
  likes encoded, DONE
  turn of the 1800s - confusing, make specific 1792 - 1805 DONE
  minimise numbers as people skim, and switch off - though 141x121 is good, move other numbers to the end
  During Winter 2021...  take out or move into bio   DONE
- Note taken on [2023-03-28 Tue 15:45] \\
  lockdown para could lead a story style bio, possibly!
- Note taken on [2023-03-21 Tue 18:43] \\
  First draft at 300 words. Ready for a polish ideally, if Gaye has time to review Wed - Fri. Ideally I'll get to meet them some eve before the weekend. I'll need to check and then clear with James O'S, or vice versa!
- Note taken on [2023-03-17 Fri 10:59] \\
  Good paragraphs, not all keepers. Next step integrate GAC technical description where appropriate.  Also consider fill in the blanks content and introduce if strong and appropriate in this section.
:END:

* A 300-500 word biographical note (written in the third person) :REV2:GREEN:
:BIO:
Mícheál Ó Catháin is a multimedia artist working primarily with performance (early Gaelic harp and voice), computer code, installation. Faithful to historical practices, Mícheál sings with the harp on his left shoulder and employs specialised fingernail techniques (which he has coined "lúthchleasa") to shape the resonance of these metal-strung instruments. His decades-long grounding in "sean-nós" singing guides his arrangements of Bunting manuscript pieces, breathing fresh life into Ireland's ancient harp music for contemporary audiences.

Mícheál works three days per week maintaining a successful engineering career in offshore renewables.  The balance of his working week is devoted to singing with the early Gaelic harp and related generative art. The crossover between Mícheál's parallel artistic and engineering careers find expression in the audiovisual exhibitions and live shows he creates, including the digital artwork shown here.

Mícheál gravitates equally towards the ancient and the emergent.  Applying his strong engineering background, Mícheál codes custom computer algorithms to make and share generative art.  This artwork reflects and nourishes his process of engaging with the early Gaelic harp on the harp's own terms.

As a multimedia artist, Micheal curates beautiful and unique audiovisual experiences for audiences across three interweaving and artistically fertile strands:
     Historical: historically viable performance of ancient harp tunes and songs from archival manuscripts and collections
     Traditional: collaborative arrangement and performance of early Gaelic harp pieces with established traditional Irish musicians and singers, returning these pieces faithfully to the living tradition
     Contemporary: improvised music and song alongside generative visual and sound art, reimagining the early Gaelic harp in contemporary contexts

Living in Cork, Mícheál is a recipient of Irish Arts Council Agility (2021), Traditional Arts Bursary (2017) and Deis Recording & Publication (2017) Awards. He has performed solo harp & voice concerts at Achill International Harp Festival and Scoil na gCláirseach Festival of Early Irish Harp, and his generative art has been exhibited at Naas Art & Culture Centre, Galway Arts Centre, and the Lord Mayor's Pavillion in Cork City.

For custom requests or general inquiries get in touch with Mícheál via contact details on his website michealocathain.com.

View and collect work from the Mícheál's Lúthchleasa [[[lu:hxlˈæsə]]] collection on the Tezos blockchain by scanning the following QR codes:



:END:
:LOGBOOK:
:LOGBOOK:
- Note taken on [2023-04-01 Sat 13:43] \\
  personality behind the work!
  unique insightful perosnal or humourous
  freedom to express myself - don't stray from subject of my artistic development
  great way to draw audience in and make more receptive
  craft a story
  omit life event, highlight whatever details I want
  if longer than 1 para, make sure it reads as a story
  who I am, not just what I do
:END:

* Note taken on [2023-03-29 Wed 19:29] [8/8]
- [X] consider early Gaelic harp instead of harp (as Irish audience) and is integral to what I do... consider performance (early Gaelic harp & voice), computer code, and installation.
- [X] esp since 2nd para mentions harp
- [X]  likes guided by the rhythms of his sean nos singing --- musical native of sean nós ---emphasise grounded from childhood.
- [X] Juxtapose my paraellel careers and the parallel nature of the work
- [X]  front load engineering ... a main theme of coming together of artistic technique and engineering techniques
- [X]  "codes custom alrog...." split into 2, or start with nourishes... on harp's own terms
- [X]  "common repertoire -> living tradition
- [X]  take out (than purely historical or traditional) ... reconsider "wider context"
  Micheal has performed as a singer and fiddle player for decades, a foundation upon which he has established a deep practice since 2011 with the early Irish harp. Since 2015 he has maintained parallel careers in art and music alongside offshore renewables 


- Note taken on [2023-03-21 Tue 14:53] \\
  consider story telling style here!
- Note taken on [2023-03-20 Mon 18:21] \\
  ;;; In recent years...Micheal has integrated digital art skills with his [existing] strong background in harp/voice performance
  ;;; As a multimedia artist, Micheal curates beautiful and unique audiovisual experiences for audiences across three interweaving and artistically fertile strands:
  ;;; Historical: historically viable performance of ancient harp pieces from archival manuscripts and collections
  ;;; Traditional: arrangement and performance of historical repertoire, returning these pieces faithfully into the common repertoire
  ;;; Contemporary: performance of improvised music, with associated generative artwork and digital sound art, bringing the early Irish harp;;; into a wider context (than purely historical or traditional) for contemporary audiences
  ;;; *ambitious*
  ;;; Micheal develops and programs algorithms (computer code) representing rules [within which unique visual art pieces are generated]
  ;;; generative visual art reacts in real time to sampled or generated harp audio...
  ;;; carefully incorporating randomness so that audiovisual experience is ever-evolving and unique
  ;;; high quality digital archival prints, working with fine-art printers (and framers)
  ;;; situating his digital art in the arc of art-history ... contemplating the place of generative coded art in the wider arc of art-history...
  ;;; using computer code as a medium for padding out the full spectrum of viable possibilities suggested by the sparse archive of harp music
  ;;; engaging with the digital archive using digital tools
  ;;; engaging with the affordances emerging digital software and hardware... (ref essay), to create immersive audiovisual installation experiences for audiences
  ;;; During a 2017 Traditional Arts Bursary Micheal began painting his emotional response to music encoded in the Bunting harp manuscripts. A 2020 Kildare Council [Local Authority Arts] Grant saw Micheal combining this physical artwork with creative coding, drawing on his engineering background, towards and exhibition and concert at Naas Arts & Culture Centre.  ...expand this to Galway Arts Centre...
  ;;; Micheal is an emerging multimedia artist working with live harp & voice performance and audiovisual exhibitions.
  ;;; Micheal has performed as a singer and fiddle player for decades, a foundation upon which he has established a deep practice since 2011 with the early Irish harp.  [Mention time split / parallel careers?]
- Note taken on [2023-03-17 Fri 11:11] \\
  250 words or so, still short.  Can customise and elaborate generously, using my what,how,why prompts and fill in the blanks, and also original bio I provided GAC.
:END:

* A 500-1000 word reflection on your artistic practice, in the context of the artworks which have been selected for the book. :REV2:GREEN:
:REFLECTION:

- Singing is at the centre of my artistic practice. Orbiting this centre is the music of the early Gaelic harp (an example of an early Gaelic harp familiar to most Irish people is the Trinity harp stamped on our coins). As a multimedia artist I integrate fine-art digital print, audiovisual installation and live performance to connect outwards from this centre with contemporary audiences. Creating both online and in-real-life (IRL) experiences rooted in the oral traditions I have inherited, I engage the emotions of today's viewer in order to make heart-felt connections with my subject matter, the harmonic nature of singing with harp. I want my audiences to have a visceral, kinesthetic response to my work; only afterwards realising it was made using computer code.

- I consider the singing human larynx as an original, primal, embodied technology with infinite possiblilities of movement, sensitively influencing the flow of breath and making it audible through resonance. I make connections between singing and the technology we make - ancient carbon-based technology like the early Gaelic harp and newly emerging silicon-based digital "Web 3.0" technologies built on the blockchain concept.  For me the very old and the very new are similarly fertile creative spaces in the global village, folding over onto each other from opposite ends of the same spectrum.

- I don't gravitate towards academic study of early Gaelic harp music. Instead I take an experimental approach, curating experiences of resonance using my own voice and body in collaboration with my harp, and a range of multimedia technologies. I have come to understand that my approach needs to be iterative, playful and curious. 

- Generative art has an established place in art history, pioneered in contempory settings by such artists as Vera Molnar (visual art) and John Cage (music composition).  The early careers of these artists were in the pre-computer era, when their rule-based algorithms incorparating chance procedures were implemented with traditional art forms such as painted canvas and orchestra. Nowadays generative art is enjoying a renaissance, created by artists using modern computer languages and presented using a cornucopia of both mature technologies of ever increasing fidelity (such as fine-art inkjet printers and multi-channel audio speakers), as well as newer internet-enabled fixed and mobile devices (such as 8K+ smart displays, and smart phones/tablets). Happily, estabished and emerging digital media such as these are ideal playgrounds for generative artists like myself to make and share work, since these media are specifically designed to afford combined visual and musical forms, and also since these media reach a global audience via the internet browser. 

- During a 2017/2018 Irish Arts Council bursary I began painting my emotional response to early Gaelic harp music encoded in the Bunting manuscripts. Since I have a strong engineering background I subsequently combined this physical artwork with creative coding. I chose the internet browser as my primary medium after researching a broad range of computer languages over the course of 2020 and 2021.  My "virtual studio" ecosystem now comprises a text editor called emacs, code written in a computer language called clojurescript, with an internet browser window open on my screen rendering audiovisual outputs from my code as I work.  Working in this way I have come to realise how well suited to my process are physical exhibitions and solo harp/voice concerts. This realisation came when I demonstrated to myself that I can render to high-resolution, and then print, the art I make in and for the browser. I access the best of both worlds - the reach and facility of the browser, with the warmth, texture and visual fidelity of fine-art prints.  As well as exhibitions and performances, I find inspiration in sharing my work in progress with like-minded artists. This type of sharing is typical of many generative artists who regularly share their work in progress, as do I, on a variety of social media platforms. 

- I am drawn to the subject of musical resonance because it is a universal human experience which finds regional and personal expression. This has led me to think about whether the visual art on the Trinity harp - which incorporates Celic knot-work, overlaid lozenges, circular motifs and gemstones - expresses similar ideas to those represented by the music the harp for was physically designed for. In my Lúthchleasa [[[lu:hxlˈæsə]]] collection I explore this thought with abstract visual forms and sound samples.

- I am investigating my belief that there is a link between the resonating patterns expressed in early Gaelic art and harp music.  I believe these patterns are structured on geometric rules, with variation from the rules an idiomatic feature expressible with randomness.  I don't consider the music collected by Bunting to be a static unchanging set of relics.  Creating his manuscripts, Bunting did an outstanding job preserving the old harp music as he did, with a rich trail of clues as to how his Western classical music interpretation could be reverse-filtered. However if the medium is the message, then the message of a manuscript is that what it contains is unchanging, frozen.  Intuitively I don't believe this is true of the music of the early Gaelic harp, and thankfully our new digital audiovisual media can do justice to expressing this inherently oral tradition on its own terms. I am convinced the musical ideas contained in the Bunting manuscripts, and other related archival collections, represent datapoints in a rich and dynamic spectrum of possibilities. In my  Lúthchleasa [[[lu:hxlˈæsə]]] collection, I explore and reimagine this spectrum using computer code to create visuals and sounds with simple rules overlaid to effect emergent complexity, using primitive geometric shapes and randomness.  

- To me Lúthchleasa [[[lu:hxlˈæsə]]] represents a mindfully curated attention echo-chamber, appropriating the latest emerging technology to amplify for myself and for audiences the ideas of resonance as represented in early Gaelic harp music and art. In the process of creating Lúthchleasa [[[lu:hxlˈæsə]]], some ideas crystalised as I hoped while others proved too ambitious in the timescales available and so form the seeds for future work!
:END:
:LOGBOOK:
- Note taken on [2023-04-02 Sun 18:11] \\
  Good para but cut as hard to located and pushes me over wordcoutn...
  
  - My questioning of conventional interpretations of the music encoded in the Bunting manuscripts is expressed in the curation of the Fearn series prints at Galway Arts Centre, where I chose not to mount the pieces on the wall but rather flat on a display table, suggesting and encouraging another point of view.
- Note taken on [2023-03-29 Wed 19:53] \\
  Martin likes the mental picture
  resonance is over-used! DONE
  mozart rolled dice...  aleatoric - Ludisofsky 20thC  Fair enough , but not included DONE
  remove 1950...  DONE
  pioneered in a contemporary setting by such artists...DONE
  
  Trinity --- visual art, needs a micro introduction --- like back of coin fro the harp
  
  Elaborate on laying work flat and ... point of view
- Note taken on [2023-03-28 Tue 12:10] \\
  By geometry of early Gaelic harp music, I mean examples such as Mathieu's lattice for all the modes played on early Gaelic harp, the lines of the strings and the gaps between strings and groups of strings - mappable from the lattice.  THe geometry of my hands and my heel navigates along the soundbox and my fingers and thumbs gauge the gaps.  Compositions may be circular (piobrachd), symmetry features in ABAB parts etc, luthchleasa feel geometric - patterns which could almost certainly be mapped to a geometric shape....
- Note taken on [2023-03-26 Sun 12:09] \\
  Gen visual and audio pioneer section needs work!
- Note taken on [2023-03-26 Sun 11:19] \\
  improvisational nature of harp...
  
  share this writing with Ann!
- Note taken on [2023-03-26 Sun 10:59] \\
  Web technologies democratise traditional arts
- Note taken on [2023-03-26 Sun 10:35] \\
  Gaye feedback:
  For my part I found it most interesting and engaging. I completely understood your motivation and intention and your emotional connection the art, music and coding.  Really interesting.  I was quite excited to see the art pieces which are beautiful. Loved the signficance of the paper.
  
  Chris feedback:
  Loved the combining of the very modern as in the coding with the ancient. 
  ...paraphrase... he really got my idea that the oral tradition was one filled with variation and how I see coded audiovisual media are much closer to an oral tradition for the global village, as being more suitable to representing this tradition for today, and that that the print technology of Bunting's era brought with it an independent message (which has been convoluted across the general understanding of early Gaelic harp music) that the musical "snapshot" was fixed, unvarying.  This idea is validated by audio recording era folk and sean nos singers... such as Colm Ó Caoidheáin and Sorcha Ní Ghuairim, as well as instrumental artists such as ... performing the same song in different ways on different occassions sometimes years apart.
- Note taken on [2023-03-26 Sun 10:32] \\
  About to start rewrite! Rev2 here goes!
- Note taken on [2023-03-21 Tue 17:11] \\
  At 990 odd words. Well done me! I'll call that a first draft :)
- Note taken on [2023-03-21 Tue 16:41] \\
  What about Agnes Martin ... music is accepted as pure emotion, but from art they demand explanation.  Also didn't Af Klimt talk about music and visuals, also Josef Albers....
- Note taken on [2023-03-21 Tue 16:38] \\
  I do find it really valuable to be able to express HOW I respond in my art emotionally to music in the Bunting archive... how does they things map even if not 1:1.  Colour palettes, modes, ... what I would like to consider in Juxt!  Can I summarise a kernel on how and why I do this?  Referencing visual rhythm, harmony etc.....
- Note taken on [2023-03-21 Tue 14:28] \\
  Copying to new BLUE tag and cutting out all hard and fast linkage between early Irish art and my artwork
- Note taken on [2023-03-21 Tue 14:28] \\
  I don't want to make a target for my own back.  A standard to be held to with all my visual art. I choose artistic freedom.
- Note taken on [2023-03-21 Tue 08:12] \\
  Embrace that I'm at early stages.  I'm setting up conditions for my further exploration of luthchleasa LONG TERM.  Its about the ecosystem, boundaries, conditions in which my exploration, experimentation, thrives.
- Note taken on [2023-03-21 Tue 07:54] \\
  Discussion with Gaye and Chris might help to tease out how I express whether singing, or singing and harp is at the centre of my art.  Really it is an intention.  I want to create conditions conducive to me singing daily, with harp, in a world in which voice and resonance in the body, or wrapped around a resonanting harp, is atrophying down the senses and body parts which can engage with the tiny reduced affordances of technologies designed without .... e.g., Ge's image of a giant eye on a finger, as seen by the computer!
- Note taken on [2023-03-20 Mon 18:23] \\
  ;; Structures:
                ;;; storytelling - beginning, middle and end
                ;;; medium / process / understanding of the work (with strong, attention grabbing, end sentence)
                ;;; field notes (use words to create curiosity, share info and provoke closer examination of subject and form)
                ;;;; para to describe where you are, or what exploiring (the general caption)
                ;;;; notes re individual pieces (with attributes)
                ;;; (always lead back to what viewers are seeing)
- Note taken on [2023-03-20 Mon 12:14] \\
  I wish to remain sufficiently general so that I avoid hemming in my artistic freedom, while still expressing the why and worthiness of my harp-specific work so that audiences / viewers will take a closer look at my work (both specifically and overall).
:END:



* Notes from Art Write prompts etc
  :LOGBOOK:
  - Note taken on [2023-04-02 Sun 20:53] \\
    ;;; people, this is who I am
    ;;; highlights of my artistic development, but not detail anyone could get from my resume              
    ;;; Micheal O'Cathain enjoys telling people he once...
    ;;; Youghal!
    ;;; Parallel career...
  - Note taken on [2023-04-02 Sun 20:35] \\
    ;;; In recent years...Micheal has integrated digital art skills with his [existing] strong background in harp/voice performance
    ;;; As a multimedia artist, Micheal curates beautiful and unique audiovisual experiences for audiences across three interweaving and artistically fertile strands:
    ;;; Historical: historically viable performance of ancient harp pieces from archival manuscripts and collections
    ;;; Traditional: arrangement and performance of historical repertoire, returning these pieces faithfully into the common repertoire
    ;;; Contemporary: performance of improvised music, with associated generative artwork and digital sound art, bringing the early Irish harp;;; into a wider context (than purely historical or traditional) for contemporary audiences
    ;;; *ambitious*
    ;;; Micheal develops and programs algorithms (computer code) representing rules [within which unique visual art pieces are generated]
    ;;; generative visual art reacts in real time to sampled or generated harp audio...
    ;;; carefully incorporating randomness so that audiovisual experience is ever-evolving and unique
    ;;; high quality digital archival prints, working with fine-art printers (and framers)
    ;;; situating his digital art in the arc of art-history ... contemplating the place of generative coded art in the wider arc of art-history...
    ;;; using computer code as a medium for padding out the full spectrum of viable possibilities suggested by the sparse archive of harp music
    ;;; engaging with the digital archive using digital tools
    ;;; engaging with the affordances emerging digital software and hardware... (ref essay), to create immersive audiovisual installation experiences for audiences
    ;;; During a 2017 Traditional Arts Bursary Micheal began painting his emotional response to music encoded in the Bunting harp manuscripts. A 2020 Kildare Council [Local Authority Arts] Grant saw Micheal combining this physical artwork with creative coding, drawing on his engineering background, towards and exhibition and concert at Naas Arts & Culture Centre.  ...expand this to Galway Arts Centre...
    ;;; Micheal is an emerging multimedia artist working with live harp & voice performance and audiovisual exhibitions.
    ;;; Micheal has performed as a singer and fiddle player for decades, a foundation upon which he has established a deep practice since 2011 with the early Irish harp.  [Mention time split / parallel careers?]
    
    ;;; coffee fodder...
    ;;;; my art is about / my art reconciles the locally disintegrating with the globally emerging ... (6 words)
    ;;;; my art is about explaining my culture to myself (5 words)
    ;;;; my art is about contextualising my cultural inheritance.... (4 words)
    ;;;; my art is about loving every breath... (3 words)
    ;;;; my art is about singing colours ... (2 words)
    ;;;; my art is about singing (1 word)
    
    ;;; Seamus Begley's story on Se mo laoch about his mother waiting to be asked to sing, and being annoyed when not asked - needing the right social context to be sufficiently relaxed to sing (knowing she couldn't rightly be judged?) ... a very particular Irish context even though she sang pop songs and with vibrato...  A universally human experience - we all need to feel we have fulfilled certain social conditions (norms) before we can "sing".  Art helps (me  /  us) navigate and find these balances
    ;;;
    
    ;;; choosing a few, well chosen words about what I do is a way of being considerate towards my listeners, because they can always ask more questions, and of making me sound more confident.
    ;;; speak up! confidence and enthusiasm are the very best self-promotion tools
    
    ;;; prepare something brief to say about yourself and your work
    ;;; the way you speak about yourself and your work sends people to the intended destination: your art!
    ;;; the handshake speech: (implies some kind of connection takes place - imagine someone extending their hand to me... a stranger... a gallery owner, collector...)
    ;;; a performance, write my lines, know my lines!
    ;;; .....
    ;;;; Hi, my name is ... , I'm an artist
    ;;;; I work in ... mediums
    ;;;; My art is about ....
    ;;;; Right now I'm working on ....
    ;;;; I live ... place, my studio is .... place
    ;;;; You can see my work [online or gallery]
    ;;; This is a good time to hand them a business card
    ;;; Really important to be prepared to ask a question, e.g., Are you an artist
    ;;; If quezy with all the sales pitch, remember my art is the treasure and everything else is the map :)
    ;;; rehearse out loud! don't miss opportunities to make connections and sales through lack of prep
  - Note taken on [2023-04-02 Sun 20:33] \\
    ;; A 500-1000 word reflection on your artistic practice, in the context of the artworks which have been selected for the book.
                  ;; wordcount...
    
                  ;;;; 1. how did I make this?
                  ;;;; with computer code written in a language called clojurescript, and using a graphics library called p5.js (and a audio environment called ChucK - mention in process moreso perhaps!)
                  ;;;; working with a fine-art printer to convert the digital pixels in a .tif file to a print on archival paper
                  ;;;; 2. how did I use the medium or combine mediums?
                  ;;;; Because it was uncertain if the exhibition would be in-person or virtual, I created the work so that it could be viewed online by anyone using an internet browser, as well as printing physical fine-art prints of the images for mounting in the physical exhibition space
                  ;;;; By designing my digital canvas in the browser to scale easily to any resolution I wanted, it became feasible to seamlessly combine the two mediums, ie of a LCD screen displaying a digital image on a browser canvas, and a physical print of the same image.
                  ;;;;              
                  ;;;; 3. how did i phyically engage in the creation?
                  ;;;; I created the images by sitting at a desk, writing code using a computer keyboard, and viewing the results on a computer screen
                  ;;;; Visited the gallery space and through discussions with the gallery team as well as mentorship, decided that displaying the images horizontally rather than the traditional vertical mounting was appropriate, both for the pieces and for architecture of the room.
                  ;;;; 4. how is it constructed?
                  ;;;; The tables had been built for a previous Tulca exhibition, glass tops were cut to measure at a local framer on Dominic Street
                  ;;;;
                  ;;;; 5. how am i uniquely presenting the subject?
                  ;;;; By presenting the pieces horizontally
                  ;;;; By abstracting the notes and staves in the Bunting manuscripts, playing with their structure and introducing colour
                  ;;;;              
                  ;;;; 6. how did accidents or discoveries lead me to the finished work?
                  ;;;; I discovered that carefully introducing randomness into the underlying grid gave a softer more organic feel to the overall composition
                  ;;;;              
                  ;;;; 7. how did I choose this medium?
                  ;;;; I chose the browser as my primary medium by researching a broad range of computer languages over the course of the pandemic.  It became apparent to me how much of human time and attention globally is spent within this browser environment. I also realised how powerful a multimedia medium the browser is already, with additional features being added by browser designers on a daily basis.  A big ah-ha moment was when I demonstrated to myself that I could render to high-resolution and print the art I made in and for the browser, so that I could access the best of both worlds - the reach and facility of the browser with the warmth, texture and visual fidelity of a fine-art print.
                  ;;;;              
                  ;;;; 8. how did I choose this subject?
                  ;;;; 
                  ;;;;              
                  ;;;; 9. how did I decide on this direction?
                  ;;;;
                  ;;;;              
                  ;;;; 10. how has exploration brought me to this work?
                  ;;;;
                  ;;;;              
                  ;;;; 11. how would I like the viewer to approach the work?
                  ;;;; With awareness of their point of view, an awareness encouraged by the choice of the artist to display the pieces in the horizonal (reminiscent to how museum pieces are displayed) rather than the more traditional choice of vertical wall mounting 
                  ;;;; a curiosity about how accessible we feel the music represented in the art to be
                  ;;;;               
                  ;;;;              
                  ;;;; 12. how did I choose my palette?
                  ;;;; gradient of reds to yellow-greens in "north to south" direction, with a gradient of blue-greens to violets in the "west to east" direction
                  ;;;;              
                  ;;;; 13. how would I decribe the continuity or contrast in the work
                  ;;;;
                  ;;;;              
                  ;;;; 14. how does the subject relate to the form, the form to the subject?
                  ;;;; The form of the pieces comprises intersecting music staves and paths reminiscent of Celtic knot-work, with clouds of msusical note-heads.  The subject of the Fearn series are four lúthchleasa, with the "action" of these techniques related to the structure and suggested motion of the forms.  The lúthchleasa represented are ...  
                  ;;;; The strings of the harp are also suggested by the form
                  ;;;; Colour of the pieces represents the emotional content of these techniques
                  ;;;;              
                  ;;;; 1. what is the viewer looking at?
                  ;;;; A series of 7 prints, each 141x121mm on Hahnemuhle archival paper, presented on top of a display table covered with glass
                  ;;;;              
                  ;;;; 2. what is it made of?
                  ;;;; archival ink on Hahnemuhle paper
                  ;;;;              
                  ;;;; 3. what was my process?
                  ;;;; I coded an algorithm which generates variable outputs, each image unique and repeatable based on a digital signature which determines all randomness in the image. Think of this signature as a seed or "DNA" for all the variability of the image. From a set of circa 200 unique images generated by the algorithm, I curated 15 images for printing and display in the exhibition on two tables. 7 of these images are shown in the photograph.
                  ;;;;              
                  ;;;; 4. what does it represent?
                  ;;;; The Fearn series of generative artwork represents my emotional response to a specific family of harp techniques (a subset of the full set of lúthchleasa) named in the Bunting as leath leagadh, leagadh anuas, brisidh and crothach aon mhear. From my own experience of playing these techniques, I have grouped them together and assigned (as a memory aid) the ogham symbol Fearn to identify this grouping.
                  ;;;; The noteheads "escaping" from the staves represents the release of the notes from the "straigh-jacket" / limitations of European music notation             
                  ;;;; 5. what am I investigating?
                  ;;;; I am investigating my own intuitive approach to re-animating ancient Irish harping finger-nail techniques, which I collectively refer to as lúthchleasa.  The artwork provides me a framework on which to record my interpretation of these lúthchleasa, the visual medium of generative art serves to represent visually attributes which I map from my physical playing of these techniques on my harp and the sounds which results.
                  ;;;;              
                  ;;;; 6. what am I combining or breaking apart?
                  ;;;; I am breaking apart / separating / categorising the families of techniques, and examining their attributes
                  ;;;;              
                  ;;;; 7. what was the initial inspiration and where the it lead?
                  ;;;; 
                  ;;;;              
                  ;;;; 8. what could I say that might encourage a closer look?
                  ;;;; There is a lot of fine detail in the noteheads
                  ;;;; The attributes of the techniques are mapped to the visuals of each piece in the Fearn series, as indicated by the names of each piece.             
                  ;;;; 9. what am I communicating?
                  ;;;; I am communicating my range of responses to the lúthchleasa, representing these responses in visual form to share the emotional, musical, linguistic and physical attributes I associate with each of these lúthchleasa.
                  ;;;;              
                  ;;;; 10. what story does it tell?
                  ;;;; It tells the story of my engagement with these lúthchleasa, as I deepen my understanding of these techniques and the musical ideas they represent.  The nature of generative art is that it is iterative, so I expect to build my story into future versions of the code, and the art work which emerges,  as my understanding and playing of these lúthchleasa techniques on my harp evolves.
                  ;;;;              
                  ;;;; 11. what did I learn while making it?
                  ;;;; 
                  ;;;;              
                  ;;;; 12. what pervades the work?
                  ;;;;
                  ;;;;              
                  ;;;; 13. what qualities characterises the work
                  ;;;;
                  ;;;;              
                  ;;;; 14. what did I accomplish
                  ;;;;
                  ;;;;              
                  ;;;; 15. what keeps me curious, dedicated or obsessed?
                  ;;;; The richness of the early Irish harp and visual art traditions keeps me curious and dedicated, especially how to find contemporary and appropriate settings for expressing the ideas for which this instrument and the music it can make is uniquely suited.
                  ;;;;              
                  ;;;; 16. what was involved? collarboration, tools, skills, travel, research, technoclogy, more than one attempt?
                  ;;;; The artwork involved mentorship (both musical with Ann Heymann and visual with Louise Manifold), skills in computer coding of visuals and audio in the browser, travel between Dublin (where I lived at the time) and Galway Arts Centre for site visits and well as production of the exhibition, technology in multiple forms - print, photo, video, computer hardware, remote monitoring of audio visual installation, electronic effects during live performance. 
                  ;;;;              
                  
                  
                  ;; why (intention, i.e., my understanding of my work)
                  ;;; if struggling with expressing thinking behind my artwork, focus my writing on physical making of my work, the process, or development of form
                  ;;; also what drives me to express myself visually / sonically
                  ;;; it is possible to be abstract in my ideas while still being concrete in my language
                  ;;; bring out inner ambassador, enthusiast, teacher...(or best communicator I know)... keep inner critic at arms' length!
                  ;;;
                  ;;;; 1. why did I make this?
                  ;;;; to map out visually the idea of luthchleasanna
                  ;;;; to give each their territory visually, sufficient to explore long term as my understanding of their emotional content evolves
                  ;;;; 2. what do I believe in?
                  ;;;; predictable, repeatable human emotional response is hard-coded into the techniques
                  ;;;; these responses can be mapped visually, individually and overlapping             
                  ;;;; 3. what belief am I investigating?
                  ;;;; there is a link between the ideas expressed visually and sonically in early Irish music and art
                  ;;;; theses ideas are rule-based, geometric, with variability / deviations from the rules expressible with randomness
                  ;;;; that music collected by Bunting represents datapoints in a broad dynamic spectrum, not static unchanging relics
                  ;;;; this spectrum can be reconstructed, using digital art forms and ideas of geometry and randomness
                  ;;;; 4. how does personal belief or viewpoint or conviction come through in my art?
                  ;;;; primative geometric shapes, random distributions of same, combination of attributes resulting in emergent complexity
                  ;;;; linking music and visuals, both in exhibition/installation, and also in live performance
                  ;;;; my questioning of conventional interpretations of the music represented in the Bunting manuscripts is expressed in the curation of the Fearn series in GAC, where I chose not to mount the pieces on the wall but rather flat on a display table.
                  ;;;; 5. what emotion was primary while I made this artwork?
                  ;;;; surprise, wonder, esp when I introdcued randomness into grid of Fearn... carthesis (sail), 
                  ;;;;              
                  ;;;; 6. how does emotion come through the work?
                  ;;;; colour, juxt of hardlines and relaxed structure, notes "flying" away, released from strait jacket
                  ;;;;              
                  ;;;; 7. what was I thinking about during the process?
                  ;;;; paths, staves, notes ... Bunting manuscript layers, reverse engineering the layers from the compound image
                  ;;;; affordances of the browser - linking soudns and visuals             
                  ;;;; 8. what inspired this direction?
                  ;;;; Ann convos during Bursary, painting during Bursary, Dan S tuturials, frustration of not relating to accepted wisdom of historically informed practice, 
                  ;;;;              
                  ;;;; 9. if the inspiration had no concrete logic, write about that!
                  ;;;; i relaxed the need to directly link visuals to music, as this allowed the unknown / gaps in the Bunting music to fill themselves in - also this honoured my own intuition from being imbibed in traditional singing and dance music.
                  ;;;;              
    
    
    
                  
                  ;; fill in the blanks
    
                  ;;; 1. I work in ... form/medium/theme because it allows me to ... [action/expression]
                  ;;; 1. I work in generative art, installation and performance because it allows me to engage with diverse contemporary audiences to reanimate the richness of ideas represented in early Irish harp music, song and art.
                  
                  ;;; 2. I ... [verb] the viewer in order to ... [state my intention]
                  ;;; 2. I engage the emotions of the viewer in order to make heart-felts connections with my subject matter, the resonance of singing and harp music.
    
                  ;;; 3. I created ... [the work] to express my ... [belive/emotion/idea] concerning/and ... [the situation/inspiration]
                  ;;; 3. I created the Lúthchleasa exhibition to express my emotional response to the music encoded in the Bunting manuscripts.
                  ;;; 3. I created the Fearn series to express my visual mapping of musical attributes associated with four specific fingernail techniques (Lúthchleasa) recorded by Bunting from the last of the early Irish harpers in the 1790s.
    
                  ;;; 4.  .... [clearly describe a particular piece in the show] is based on [reference or experience]
                  ;;; 4.  The 121x142mm dimensions of each piece in the Fearn series is based on the dimensions of Edward Bunting's field notebook, while the paper chosen () is mindful of the laid-paper technology which had recently emerged at the time Bunting collected this harp music. 
    
                  ;;; 5. I am drawn to the subject ... because ...
                  ;;; 5. I am drawn to the subject of musical resonance because it is a universal human experience which finds regional and personal expression.
                  ;;; 5. I am drawn to the subject of early Irish harp, song and art because of my conviction that they respresent ancient forms of soul nourishment which remain relevant today. 
                  
                  ;;; 6. In the process of creating this work, ...
                  ;;; 6. In the process of creating this work, I gained the experience of successfully delivering an ambitious multimedia exhibtion.
                  ;;; 6. In the process of creating this work, some ideas crystalised as I hoped while others proved too technically challenging and formed the seeds for future work.
    
                  ;;; 7. I want my viewer to ...
                  ;;; 7. I want my viewer to have a visceral, heart-felt response to my work; only afterwards realising/learning it was created using computer code.
    
                  ;;; 8. I discovered that my approach needed to be ....
                  ;;; 8. I discovered that my approach needed to be iterative and experimental
                  ;;; 8. I discovered that my approach needed to be of the hand-curated variety rather than of the long form variety, given both the artisic and technical challenges of the latter.              
    
                  ;;; 9. I find inspiration ...
                  ;;; 9. I find inspiration in sharing my work in progress with like-minded artists; this type of sharing is the M.O. of many generative artists who regularly share their work in progress, as do I, on a variety of social media platforms.
    
                  
                  ;;; 10. ... is at the centre of my art
                  ;;; 10. Singing is at the centre of my art
                  ;;; 10. Breathing and resonance is at the centre of my art                            
    
                  ;;; 11. I don't ..., instead I ...
                  ;;; 11. I don't gravitate towards academic study of early Irish harp music, instead I take an experimental approach, curating experiences of resonance using my own voice and body in collaboration with my harp, and a range of multimedia technologies.
                  
                  ;;; 12. My work is a combination of ... and ...
                  ;;; 12. My work is a combination of play and cultural inheritance.
                  
                  ;;; 13. To me the most important thing is ...
                  ;;; 13. To me the most important thing is singing.              
    
                  ;;; 14. I make connections between ... and ...
                  ;;; 14. I make connections between singing and technology - ancient techology like the early Gaelic harp and emerging technology like web3 / blockchain.
    
                  ;;; 15. To me this represents ...
                  ;;; 15. To me this (show) represents a mindfully curated attention echo-chamber, appropriating the latest emerging technology to amplify for myself and for the viewer - even for a short while - the ideas represented in early Gaelic harp music and art.
    
                  ;;; 16. I was thinking about ... and I created ...
                  ;;; 16. I was thinking about whether the art on the trinity harp represents the same ideas as those represented by the music it is designed for, and I created the Lúthchleasa exhibition which explores this idea with abstract forms and sound samples.
    
    
                  ;; Structures:
                  ;;; storytelling - beginning, middle and end
                  ;;; medium / process / understanding of the work (with strong, attention grabbing, end sentence)
                  ;;; field notes (use words to create curiosity, share info and provoke closer examination of subject and form)
                  ;;;; para to describe where you are, or what exploiring (the general caption)
                  ;;;; notes re individual pieces (with attributes)
                  ;;; (always lead back to what viewers are seeing)
  :END:
